flavor: small
os: rhel
source:
  pvc:
    name: centos8-stream-downstream
    namespace: kubevirt-data-volumes
instances: 1
platform: openshift
diskSize: 20Gi
# nameOverride:
#ports:
#  - name: https
#    port: 443
#    backendPort: 8443 # optional - defaults to port
#    protocol: TCP # optional - defaults to TCP
service:
  annotations: {}
  type: ClusterIP

apache:
  enabled: false
  version: latest