flavor: small
os: linux-centos8
instances: 1
platform: openshift
diskSize: 20Gi
# nameOverride:
#ports:
#  - name: https
#    port: 443
#    backendPort: 8443 # optional - defaults to port
#    protocol: TCP # optional - defaults to TCP
service:
  annotations: {}
  type: ClusterIP

apache:
  enabled: false
  version: latest