{{ if and (.Values.ports) (eq "openshift" .Values.platform ) }}
{{- range $key, $val := .Values.ports }}
{{- if not (kindIs "invalid" $val.ingress) }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    name: {{ include "vm.name" $ }}
    cluster: {{ include "vm.name" $ }}
    os: {{ $.Values.os }}
  name: {{ include "vm.name" $ }}-{{ $val.name }}
{{- if $val.ingress.annotations }}
  annotations:
    {{- toYaml $val.ingress.annotations | nindent 4 }}
{{- end }}
spec:
  host: {{ $val.ingress.host }}
  path: {{ default "/" $val.ingress.path }}
  port:
    targetPort: {{ .name }}
  tls:
    insecureEdgeTerminationPolicy: {{ default "Redirect" $val.ingress.insecureEdgeTerminationPolicy }}
    termination: {{ default "edge" $val.ingress.termination }}
  to:
    kind: Service
    name: {{ include "vm.name" $ }}
    weight: 100
  wildcardPolicy: None
{{ end }}
{{- end }}
{{- end }}