# permissions for end users to edit virtualmachineclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachinecluster-editor-role
rules:
- apiGroups:
  - apps.baloise.dev
  resources:
  - virtualmachineclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.baloise.dev
  resources:
  - virtualmachineclusters/status
  verbs:
  - get
