# permissions for end users to view virtualmachineclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachinecluster-viewer-role
rules:
- apiGroups:
  - apps.baloise.dev
  resources:
  - virtualmachineclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.baloise.dev
  resources:
  - virtualmachineclusters/status
  verbs:
  - get
